### ISSUE TITLE
move Submodule from SSH to https

### ISSUE THREAD

**Issue by fuog** [unixorn/kubectx-zshplugin#11]
Hi,
would it be possible to use HTTPS instead of SSH on the submodule?
i ran into problems when trying to poll your repo innkl submodules because my client runs partially in a restrictive environment. ( proxy, no ssh )

thanks

**Comment by unixorn** [comment]
I'm using ssh on the submodule so `git` can pick up the ssh key from a user's `ssh-agent` and not have to type in credentials every time their shell framework checks for updates.

**Comment by unixorn** [comment]
As a workaround, you can clone it into a directory, then update your framework to look at the local directory copy instead of at the version on github - at least then you can do manual updates as needed.

**Comment by fuog** [comment]
sure https + restricted git-repos is impractical, but this is a public repo which allows everyone read-only. 
anyone can make `git clone https://github.com/unixorn/kubectx-zshplugin.git` without creds

would be nice if it was https, but i can also code around the problem.

**Comment by warbaque** [comment]
I am also using my shared zshrc with accounts without any ssh keys or credentials. I see no downsides of using https for read only pulling.

**Comment by unixorn** [comment]
@fuog, @warbaque Fair enough. Open a PR and I'm happy to merge it and tag it `hacktoberfest-accepted` so you get credit for it in this year's hacktoberfest

**Comment by unixorn** [comment]
Closed by #12
