### ISSUE TITLE
No such file or directory ERROR

### ISSUE THREAD

**Issue by dbuteau** [unixorn/kubectx-zshplugin#3]
Hello! 
I was applying the readme.md for Oh-my-Zsh install and at the last step (reloading zsh) i encountered this:
```
$ source ~/.zshrc
/home/me/.oh-my-zsh/custom/plugins/kubectx/kubectx.plugin.zsh:source:10: no such file or directory: /home/me/.oh-my-zsh/custom/plugins/kubectx/kubectx/completion/kubectx.zsh
/home/me/.oh-my-zsh/custom/plugins/kubectx/kubectx.plugin.zsh:source:11: no such file or directory: /home/me/.oh-my-zsh/custom/plugins/kubectx/kubectx/completion/kubens.zsh
```

To fix this, please:
- in the readme.md update the line 
`git clone https://github.com/unixorn/kubectx-zshplugin.git kubectx` by `git clone --recursive https://github.com/unixorn/kubectx-zshplugin.git kubectx`

This to avoid executing this additional commands to get the missing files (if another people encounter this error, please do the following):
```
cd ~/.oh-my-zsh/custom/plugins/kubectx/
git submodule init
git submodule update
```
indeed `git clone` command alone doesn't download submodule automatically

In add, if you allow me to comment the remote choice:
i think it's simpler if the submodules remote uri is an https uri, git@ using ssh connexion can be complex for peoples whom never used it before (they have to install openssh, generate private/public ssh key etc), https one work without additional configurations needs in most environments

anyway, thank for the script :)

**Comment by unixorn** [comment]
Thanks for the report and detailed fix. I must have done a submodule init on my laptop.

I really need to figure out a good way to test for that kind of error.
